sudo: required
dist: trusty

language: php

php:
  - 5.6
  - 7.0

env:
  matrix:
    - magento=2.1.5
    - magento=2.1.6
    - magento=2.1.7
    - magento=2.1.8
    - magento=2.1.9
    - magento=2.2.0
    - magento=2.2.1
    - magento=2.2.2
    - magento=2.2.3
    - magento=2.2.4
    - magento=2.2.5
    - magento=2.2.6

matrix:
  exclude:
    - php: 5.6
      env: magento=2.2.0
    - php: 5.6
      env: magento=2.2.1
    - php: 5.6
      env: magento=2.2.2
    - php: 5.6
      env: magento=2.2.3
    - php: 5.6
      env: magento=2.2.4
    - php: 5.6
      env: magento=2.2.5
    - php: 5.6
      env: magento=2.2.6

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - cd $HOME
  - composer config -g http-basic.repo.magento.com $MAGE_PUBLICKEY $MAGE_PRIVATEKEY

install:
  # install magento to home directory
  - cd $HOME
  - composer create-project "magento/community-edition:$magento" ce

  # install cobby
  - cd ce
  - composer require mash2/cobby-magento2

  # update cs and standards
  - composer require squizlabs/php_codesniffer:*
  - composer require magento-ecg/coding-standard:*

  # override cobby with the commited version
  - cd $HOME/ce/vendor/mash2/cobby-magento2/
  - rm -rf *
  - cp -R $TRAVIS_BUILD_DIR/* $HOME/ce/vendor/mash2/cobby-magento2/
  - cd $HOME/ce
  - composer dump-autoload

script:
  # run phpcs
  - cd $HOME/ce/vendor
  - ./bin/phpcs --standard=./magento-ecg/coding-standard/EcgM2/ --warning-severity=6 ./mash2/cobby-magento2/
 